boostcamp-2020/Project09-C-Uber-Clone

.github/workflows/deploy.yml

- 배포 관련 설정
- secret에 필요한 환경 설정 추가
- 배포 스크립트 작성

Github Action deploy 스크립트 추가

---

client/src/components/containers/LoginForm.tsx
client/src/slice.ts

Redux와 Apollo 병합

---

client/package.json
client/webpack.config.js
server/src/models/driver.ts
server/src/models/index.ts
server/src/models/rider.ts
server/src/repositories/driver.ts
server/src/repositories/index.ts
server/src/repositories/rider.ts

User 관련 Models와 Repositories 정의
- Models: mongoose로 mongodb 스키마 정의
- Repositories: 정의된 스키마로 database에 접근하는 객체 정의
- Driver, Rider 추가

User 관련 Models와 Repositories 정의

---

client/babel.config.js
client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/containers/RiderSignUpForm.tsx
client/src/components/presentational/RiderSignUpInput.tsx
client/src/components/presentational/SignUpButton.tsx
client/src/index.html
client/src/index.tsx
client/src/pages/RiderSignUpPage.tsx
client/src/pages/SignUpSelectPage.tsx

- React Router 구현
- SignUpSelectPage 페이지 구현
- RiderSignUpPage 페이지 구현

SignUpSelect, RiderSignUp 페이지 구현

---

client/package-lock.json
client/src/components/containers/DriverSignUpFrom.tsx
client/src/components/presentational/DescriptionInput.tsx
client/src/components/presentational/Input.tsx
client/src/components/presentational/ProfileImageInput.tsx
client/src/pages/DriverSignUpPage.tsx

드라이버 회원가입에 필요한 기본 View 추가 (layout이나 배치, 이벤트 적용 X)
- Input
- ProfileImageInput
- DescriptionInput
- DriverSignUpFrom, DriverSignUpPage

드라이버 회원가입 View 추가

---

client/src/components/containers/DriverSignUpFrom.tsx
client/src/components/containers/RiderSignUpForm.tsx
client/src/components/presentational/Input.tsx
client/src/components/presentational/SignUpButton.tsx
client/src/slice.ts

- rider 회원가입 event 구현
- driver 회원가입 event 구현
- rider 회원가입 redux 상태관리 구현
- driver 회원가입 redux 상태관리 구현

SignUp 이벤트 및 Redux 상태관리 구현

---

client/package-lock.json
server/package-lock.json
server/src/graphql/resolvers/rider.ts
server/src/graphql/types/rider.graphql
server/src/services/rider.ts

Rider gql schema 정의 후 service와 resolver 추가
- Rider gql type 정의
- rider Query 삭제
- rider service에 signup 메소드 추가
- createRider resolver 추가

Rider 회원가입 API 추가

---

client/package-lock.json
client/package.json
client/src/components/containers/Map.tsx

- @react-google-maps/api 이용
- Map 컴포넌트에 구현했습니다.

Google-Map API 기본기능 구현

---

client/src/App.tsx
client/src/components/containers/DriverSignUpFrom.tsx
client/src/components/containers/LoginForm.tsx
client/src/components/containers/RiderSignUpForm.tsx
client/src/components/containers/SetCourseForm.tsx
client/src/pages/LoginPage.tsx
client/src/pages/SetCoursePage.tsx
client/src/routes/RouteIf.tsx
client/src/slices/loginSlice.ts
client/src/slices/signUpSlice.ts

경로설정 페이지 생성
토큰 여부 확인하여 라우팅
로그인/회원가입 이후 라우팅

경로설정 페이지 생성 ,라우팅 수정

---

server/src/app.ts
server/src/graphql/resolvers/driver.ts
server/src/graphql/types/driver.graphql

Subscription 서버 설정 (test포함)

---

client/src/App.tsx
client/src/components/containers/DriverCurrentPositionMap.tsx
client/src/components/containers/RiderSetCourseMap.tsx
client/src/components/containers/SetCourseForm.tsx
client/src/pages/DriverWaitingPage.tsx

- 드라이버의 실시간 위치정보를 알려주는 드라이버 대기 페이지를 구현
- 드라이버 페이지 구현
- 실시간 위치정보 받아서 rendering
- 라이더와 드라이버가 사용하는 지도가 다르므로 Map컴포넌트 이름 변경

드라이버 대기 페이지 구현(실시간 위치정보)

---

client/src/components/containers/RiderSetCourseMap.tsx
client/src/components/containers/SetCourseForm.tsx

- 현재위치를 클릭해서 출발위치를 지정했는데도, 지도 드래그를 하면 출발위치가 새로 찍히는 오류 수정
- 현재위치와 출발위치 중 하나라도 cancel되면 중간에 그려진 파란색 경로가 삭제되도록 수정

경로설정페이지 관련 버그 수정

---

client/src/components/containers/RiderSetCourseMap.tsx
client/src/components/containers/SetCourseForm.tsx
client/src/pages/DriverWaitingPage.tsx
server/src/graphql/resolvers/rider.ts
server/src/models/driver.ts
server/src/repositories/driver.ts
server/src/services/driver.ts

드라이버 알림이 뜨기까지 발생하는 버그 수정

---

client/src/apis/callRequestAPI.ts
client/src/apis/driverAPI.ts
client/src/apis/driverResponseAPI.ts
client/src/components/containers/DriverPickUpForm.tsx
client/src/components/containers/RiderPickUpForm.tsx
client/src/components/containers/RiderWaitingModal.tsx
client/src/components/presentational/DriverPopup.tsx
client/src/pages/DriverWaitingPage.tsx
client/src/queries/callRequest.ts
client/src/queries/driver.ts
client/src/queries/driverResponded.ts
client/src/queries/rider.ts
server/src/graphql/resolvers/driver.ts
server/src/graphql/resolvers/rider.ts
server/src/graphql/types/driver.graphql
server/src/graphql/types/rider.graphql
server/src/graphql/types/trip.graphql

`driverListen`,`driverResponded`,`matchedDriverState`,`matchedRiderState` 작업 내용 연경
- input type, return type 수정
- tripId, driverId 는 session storage 에 저장

드라이버 호출 기능 연결

---

client/src/apis/tripAPI.ts
client/src/components/containers/DriverInfoBox.tsx
client/src/components/containers/DriverPickUpForm.tsx
client/src/components/containers/RiderInfoBox.tsx
client/src/components/containers/RiderPickUpForm.tsx
client/src/components/containers/RiderSetCourseMap.tsx
client/src/queries/rider.ts
client/src/queries/trip.ts
server/src/graphql/resolvers/driver.ts
server/src/graphql/resolvers/trip.ts
server/src/graphql/types/driver.graphql
server/src/graphql/types/trip.graphql
server/src/models/trip.ts
server/src/repositories/trip.ts
server/src/services/trip.ts

- matchedDriverState tripId를 기준으로 필터링
- pickUpMap 버그픽스 (매칭 시 상대의 위치가 바로 지도에 표시되도록 변경)
- 탑승버튼 클릭 시 Trip상태 onBoard로 변경

matchedDriverState 필터링, pickUpMap 버그픽스, 탑승버튼 클릭 이벤트

---

client/src/App.tsx
client/src/utils/errorHandler.ts
server/src/graphql/types/driver.graphql
server/src/graphql/types/rider.graphql
server/src/graphql/types/trip.graphql

- `@isAuthorized` directive 적용
- error handler 구현
- query, mutaion에 인증 처리 추가
- server 응답에 대한 에러 처리 로직 추가

Query, Mutation에 directive 적용 및 error Handler 모듈 구현

---

client/src/apis/driverAPI.ts
client/src/apis/driverResponseAPI.ts
client/src/apis/tripAPI.ts
client/src/components/presentational/DriverPopup.tsx
client/src/pages/DriverWaitingPage.tsx
client/src/queries/callRequest.ts
client/src/queries/driver.ts
client/src/queries/driverResponded.ts
client/src/queries/trip.ts

- DriverWaitingPage,  DriverPopup에서 사용중인 API를 useMutation, useQuery로 변경
- 관련 쿼리명을 룰에 맞게 변경

Apollo Client API를 useMutation, useQuery로 변경

---

client/src/components/containers/TripCloseModal.tsx
client/src/queries/trip.ts
server/src/graphql/types/trip.graphql
server/src/services/trip.ts

Distance 오류 해결

---

client/src/components/containers/RiderWaitingModal.tsx
client/src/queries/callRequest.ts
client/src/queries/trip.ts
server/src/graphql/resolvers/rider.ts
server/src/graphql/types/rider.graphql
server/src/repositories/driver.ts
server/src/services/driver.ts
server/src/services/trip.ts

요첨범위 확대 merge오류 해결

---

client/src/components/containers/RiderWaitingModal.tsx
client/src/components/containers/SetCourseForm.tsx
client/src/pages/DriverWaitingPage.tsx
client/src/slices/mapSlice.ts

- cache 오류 해결
- 경로 선택 이후 form 초기화

cache 오류 해결 및 경로 선택 form 초기화

---

client/src/components/containers/RiderPickupPositionMap.tsx
client/src/components/containers/RiderWaitingModal.tsx
server/src/graphql/resolvers/rider.ts

- 기본 alert 제거
- 재호출 시 메시지 변경
- 호출 실패 시 alert

라이더 대기 페이지 UI 수정

---

client/src/components/containers/DrivingForm.tsx
client/src/components/containers/PickUpMap.tsx
client/src/components/containers/RiderPickupPositionMap.tsx

지도상의 불필요 옵션제거
